import React from "react";
import type { Metadata } from "next";
import compStyles from "@/components/components.module.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Navbar() {
  return (
    <nav className={compStyles.navbar}>
      <h1 className={compStyles.h1} style={{ marginLeft: "auto" }}>
        PicsVista PicsVista PicsVista PicsVista PicsVista PicsVista PicsVista
        PicsVista PicsVista PicsVista
      </h1>
    </nav>
  );
}
