import React from "react";
import type { Metadata } from "next";
import compStyles from "@/components/components.module.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Navbar() {
  return (
    <nav className={compStyles.nav}>
      <h1 className={compStyles.h1}>PicturesVista</h1>
    </nav>
  );
}
