name: Release

on:
  push:
    branches:
      - release

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest

      - uses: actions/setup-node@latest
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@latest
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-deploy-role
          aws-region: ap-southeast-2
          audience: sts.amazonaws.com

      - name: Copy to S3
        run: |
          set -e  # Exit on error
           aws s3 sync build/ s3://www.picsvista.com --delete || { echo "Sync failed"; exit 1; }

      - name: Invalidate CloudFront
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        if: ${{ env.CLOUDFRONT_DISTRIBUTION_ID != '' }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@latest
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.name,
              title: 'Deployment Failed',
              body: `Deployment failed in run ${context.runId}`
            })

      - name: Notify on success
        if: success()
        uses: actions/github-script@latest
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.name,
              title: 'Deployment Successful',
              body: `Deployment succeeded in run ${context.runId}`
            })
